### ISSUE TITLE
Adding Type Annotations

### ISSUE THREAD

**Issue by mdyousufniaz** [cools9/ElementalDB#10]
I don't see any type annotations in python files in this repo. If you want I can add them. This will help visitors to understand the code more correctly than before. Please assign me under `hacktoberfest` label

**Comment by cools9** [comment]
Yah sure do it but the thing is idk how to give that label to you if you tell me then I will

**Comment by mdyousufniaz** [comment]
I have seen that this repo has already `Hacktoberfest` label. To add label in this repo do the following:
- click on labels *(settings like icon)*
- select `Hacktoberfest`
- And that's it!

Also assign me for this issue

**Comment by cools9** [comment]
is that it and chat in discussions

**Comment by Bashamega** [comment]
> is that it and chat in discussions

chat here

**Comment by Bashamega** [comment]
@mdyousufniaz Assigned you
