### ISSUE TITLE
[FEATURE] Add DocString in python files

### ISSUE THREAD

**Issue by mdyousufniaz** [cools9/ElementalDB#23]
## **Problem Description:**
`python` files in this repo are missing **Docstring** , I want to add them according to their usage.

*Please assign me on this issue on `hacktoberfest` label*

**Comment by cools9** [comment]
done now you can

**Comment by AlexanderSanin** [comment]
@cools9 i've added one more PR for this issue https://github.com/cools9/ElementalDB/pull/34
please accept and merge

**Comment by mdyousufniaz** [comment]
@cools9 can you create a label `hacktoberfest-accepted` and label my PR's ( #17 , #19 , #31, #33 ) ?

**Comment by Bashamega** [comment]
> @cools9 can you create a label `hacktoberfest-accepted` and label my PR's ( #17 , #19 , #31, #33 ) ?

Sure

**Comment by cools9** [comment]
How do i do that

**Comment by Bashamega** [comment]
> How do i do that

don't worry, i have made it do that automatically

**Comment by Bashamega** [comment]
Should i close this issue @mdyousufniaz ?

**Comment by cools9** [comment]
Id say yes
