### ISSUE TITLE
Add a requirements.txt

### ISSUE THREAD

**Issue by Bashamega** [cools9/ElementalDB#3]

**Comment by rajmanna-dev** [comment]
I would love to contribute on this project, can you assign me under hacktoberfest label?

**Comment by cools9** [comment]
Yes but this is my first time and I don't know how to do that

**Comment by cools9** [comment]
And what exactly do you want to contribute in I won't prefer that people will talk in issues

**Comment by cools9** [comment]
> I would love to contribute on this project, can you assign me under hacktoberfest label?

Idk how to do that this is my first time

**Comment by Bashamega** [comment]
> > I would love to contribute on this project, can you assign me under hacktoberfest label?
> 
> Idk how to do that this is my first time

Just add the hacktoberfest label to the repo and issue

**Comment by Bashamega** [comment]
I have assigned you @rajmanna-dev
