### ISSUE TITLE
[FEATURE] Authentication 

### ISSUE THREAD

**Issue by cools9** [cools9/ElementalDB#36]
Make a secure auth

**Comment by Spandan-Mishra** [comment]
I would like to take up this issue.

**Comment by cools9** [comment]
Done

**Comment by Spandan-Mishra** [comment]
@cools9 can you please put the `hacktoberfest` label on this issue? i am ready to create a PR

**Comment by cools9** [comment]
Done

**Comment by Spandan-Mishra** [comment]
@cools9 i have added PR #39 for this issue. please review it
