### ISSUE TITLE
Add a contributing guide

### ISSUE THREAD

**Issue by Bashamega** [cools9/ElementalDB#4]

**Comment by rajmanna-dev** [comment]
Assign me please.

**Comment by cools9** [comment]
Ok so you can either make the readme and docs or code I would tell you to code the filters and you are technically spamming rn

**Comment by rajmanna-dev** [comment]
I would like to contribute on README and Docs. There are some duplicate issues that why I requesting both on it.

**Comment by Bashamega** [comment]
> Assign me please.

done :)
